---
title: "Figure 2 and Table 2"
output:
  word_document: default
  html_document: default
date: "2025-02-17"
---

```{r, echo = FALSE}

# Load package
library(here)

# Execute this code to run simulations and simulate data
scripts_to_run <- c(
  here("r_scripts", "simulations_figure2", "02_evidential_value.R"),
  here("r_scripts", "simulations_figure2", "03_null_effect.R"),
  here("r_scripts", "simulations_figure2", "04_publication_bias.R"),
  here("r_scripts", "simulations_figure2", "05_mild_optional_stopping.R"),
  here("r_scripts", "simulations_figure2", "06_mixed.R"))

for (i in scripts_to_run) {
  source(i)
}

```


# Figure 2
```{r}

# Create plots for figure 2
pdf(here("figures", "figure2.pdf"), height = 10, width = 10, useDingbats = F)
par(mfrow = c(3,2))
plot(zcurve_evidential_value, CI = TRUE, 
     annotation = FALSE, main = "80% power", xlab = "")
plot(zcurve_null_effect, CI = TRUE, annotation = FALSE, 
     main = "Null effect", ylab = "", xlab = "")
plot(zcurve_publication_bias, CI = TRUE, annotation = FALSE, 
     main = "Publication bias and 20% power", xlab = "")
plot(zcurve_mild_optional_stopping, CI = TRUE, annotation = FALSE, 
     main = "Mild optional stopping", ylab = "")
plot(zcurve_mixed, CI = TRUE, annotation = FALSE, main = "Mixed")
dev.off()

```


# Results reported in Table 2
## Scenario 1: 80% power
```{r, echo=TRUE}

summary(zcurve_evidential_value, all = TRUE)

```


## Scenario 2: null effect
```{r, echo=TRUE}

summary(zcurve_null_effect, all = TRUE)

```


## Scenario 3: publication bias and 20% power
```{r, echo=TRUE}

summary(zcurve_publication_bias, all = TRUE)

```


## Scenario 5: mild optional stopping
```{r}

summary(zcurve_mild_optional_stopping, all = TRUE)

```


## Scenario 5: mixed 
```{r}

summary(zcurve_mixed, all = TRUE)

```







