---
title: "Results z-curve"
output: html_document
date: "2025-01-20"
---

Load packages

```{r}
#| echo: false
#| message: false
library(readxl)
library(dplyr)
library(zcurve)
```

Load data

```{r}
zcurve_data <- read_xlsx("../data/zcurve_data.xlsx", sheet = "Sheet1")
```

Primary z-curve

```{r main_results, echo=FALSE}
# select p-values to be included in the z-curve analysis
pvalues <- zcurve_data %>%
  filter(include == "yes" & !is.na(zcurve_pvalue)) %>%
  select(zcurve_pvalue) %>%
  pull() %>%
  as.numeric()

# primary zcurve analysis
primary_zcurve <- zcurve(p = pvalues)

results <- summary(primary_zcurve, all = TRUE)
```

Figure 3

```{r echo=FALSE}
png(here("figures", "figure3.png"), width = 1300, height = 1300, res = 200)
plot(primary_zcurve, CI = TRUE, annotation = TRUE, main = "")
dev.off()
```

```{r}
plot(primary_zcurve, CI = TRUE, annotation = TRUE, main = "")
```


Proportion of studies with large power

```{r}
# Compute the required z-score to obtain 80% power
z_score <- power_to_z(0.8, alpha = 0.05)

# Calculate the number of z-scores larger than 2.85
sum(primary_zcurve$data > z_score) 

# Calculate the proportion of z-scores larger than 2.85
sum(primary_zcurve$data > 2.801582) / length(primary_zcurve$data) *100
```

